require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ClientsCompaniesController do

  # This should return the minimal set of attributes required to create a valid
  # ClientsCompany. As you add validations to ClientsCompany, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "client_id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ClientsCompaniesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all clients_companies as @clients_companies" do
      clients_company = ClientsCompany.create! valid_attributes
      get :index, {}, valid_session
      assigns(:clients_companies).should eq([clients_company])
    end
  end

  describe "GET show" do
    it "assigns the requested clients_company as @clients_company" do
      clients_company = ClientsCompany.create! valid_attributes
      get :show, {:id => clients_company.to_param}, valid_session
      assigns(:clients_company).should eq(clients_company)
    end
  end

  describe "GET new" do
    it "assigns a new clients_company as @clients_company" do
      get :new, {}, valid_session
      assigns(:clients_company).should be_a_new(ClientsCompany)
    end
  end

  describe "GET edit" do
    it "assigns the requested clients_company as @clients_company" do
      clients_company = ClientsCompany.create! valid_attributes
      get :edit, {:id => clients_company.to_param}, valid_session
      assigns(:clients_company).should eq(clients_company)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ClientsCompany" do
        expect {
          post :create, {:clients_company => valid_attributes}, valid_session
        }.to change(ClientsCompany, :count).by(1)
      end

      it "assigns a newly created clients_company as @clients_company" do
        post :create, {:clients_company => valid_attributes}, valid_session
        assigns(:clients_company).should be_a(ClientsCompany)
        assigns(:clients_company).should be_persisted
      end

      it "redirects to the created clients_company" do
        post :create, {:clients_company => valid_attributes}, valid_session
        response.should redirect_to(ClientsCompany.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved clients_company as @clients_company" do
        # Trigger the behavior that occurs when invalid params are submitted
        ClientsCompany.any_instance.stub(:save).and_return(false)
        post :create, {:clients_company => { "client_id" => "invalid value" }}, valid_session
        assigns(:clients_company).should be_a_new(ClientsCompany)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ClientsCompany.any_instance.stub(:save).and_return(false)
        post :create, {:clients_company => { "client_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested clients_company" do
        clients_company = ClientsCompany.create! valid_attributes
        # Assuming there are no other clients_companies in the database, this
        # specifies that the ClientsCompany created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ClientsCompany.any_instance.should_receive(:update_attributes).with({ "client_id" => "1" })
        put :update, {:id => clients_company.to_param, :clients_company => { "client_id" => "1" }}, valid_session
      end

      it "assigns the requested clients_company as @clients_company" do
        clients_company = ClientsCompany.create! valid_attributes
        put :update, {:id => clients_company.to_param, :clients_company => valid_attributes}, valid_session
        assigns(:clients_company).should eq(clients_company)
      end

      it "redirects to the clients_company" do
        clients_company = ClientsCompany.create! valid_attributes
        put :update, {:id => clients_company.to_param, :clients_company => valid_attributes}, valid_session
        response.should redirect_to(clients_company)
      end
    end

    describe "with invalid params" do
      it "assigns the clients_company as @clients_company" do
        clients_company = ClientsCompany.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ClientsCompany.any_instance.stub(:save).and_return(false)
        put :update, {:id => clients_company.to_param, :clients_company => { "client_id" => "invalid value" }}, valid_session
        assigns(:clients_company).should eq(clients_company)
      end

      it "re-renders the 'edit' template" do
        clients_company = ClientsCompany.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ClientsCompany.any_instance.stub(:save).and_return(false)
        put :update, {:id => clients_company.to_param, :clients_company => { "client_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested clients_company" do
      clients_company = ClientsCompany.create! valid_attributes
      expect {
        delete :destroy, {:id => clients_company.to_param}, valid_session
      }.to change(ClientsCompany, :count).by(-1)
    end

    it "redirects to the clients_companies list" do
      clients_company = ClientsCompany.create! valid_attributes
      delete :destroy, {:id => clients_company.to_param}, valid_session
      response.should redirect_to(clients_companies_url)
    end
  end

end
